module.exports = {
  content: ["./src/**/*.{js,html,svelte}", "./public/index.html"],
  safelist: [
    // ChatView 消息气泡样式
    "bg-gradient-to-br",
    "from-blue-500/95",
    "to-blue-600/95",
    "from-white/85",
    "to-white/75",
    "from-white/70",
    "to-white/60",
    "from-red-50/70",
    "to-red-100/60",
    "from-orange-50/70",
    "to-orange-100/60",
    "border-red-200/40",
    "border-orange-200/40",
    "border-white/40",
    "border-white/50",
    "border-blue-400/40",

    // 按钮样式
    "rounded-2xl",
    "px-4",
    "py-3",
    "px-5",
    "p-3",
    "max-w-lg",
    "max-w-[80%]",
    "text-white",
    "text-gray-800",
    "text-gray-600",
    "text-red-600",
    "text-orange-600",
    "text-gray-700",
    "shadow-lg",
    "hover:shadow-xl",
    "backdrop-blur-md",
    "transition-shadow",
    "duration-200",

    // 输入框和按钮
    "from-gray-100/90",
    "to-gray-200/80",
    "hover:from-gray-200/95",
    "hover:to-gray-300/85",
    "hover:scale-105",
    "to-blue-600/90",
    "hover:from-blue-600/98",
    "hover:to-blue-700/95",
    "to-blue-50/70",
    "border-blue-200/60",
    "focus:ring-blue-400/70",
    "focus:border-blue-400/80",
    "focus:ring-2",
    "focus:ring-offset-2",
    "focus:ring-offset-white/20",
    "border-gray-300/50",
    "focus:ring-gray-400/60",

    // 布局类
    "flex",
    "flex-col",
    "flex-1",
    "items-start",
    "items-center",
    "items-stretch",
    "justify-start",
    "justify-end",
    "justify-center",
    "mb-3",
    "my-3",
    "gap-3",
    "space-y-3",
    "px-6",
    "py-4",
    "h-full",
    "h-12",
    "h-5",
    "w-5",
    "w-full",
    "overflow-hidden",
    "overflow-y-auto",
    "resize-none",
    "text-xs",
    "text-sm",
    "rounded-full",
    "rounded-t-[16px]",
    "rounded-b-[16px]",
    "bg-gradient-to-b",
    "from-blue-50/20",
    "to-indigo-50/15",
    "bg-gradient-to-r",
    "from-white/50",
    "to-blue-50/40",
    "from-white/40",
    "to-blue-50/30",
    "border-t",
    "border-b",
    "border-blue-200/30",
    "scrollbar-thin",
    "scrollbar-thumb-blue-300/40",
    "scrollbar-track-transparent",
    "placeholder-gray-500",
  ],
  theme: {
    extend: {
      height: {
        "chat-view": "80vh",
      },
      width: {
        "chat-view": "60vw",
      },
      maxWidth: {
        "chat-view": "900px",
      },
      minWidth: {
        "chat-view": "600px",
      },
    },
  },
  plugins: [],
};
